### ISSUE TITLE
deprecatedProp 合并错误

### ISSUE THREAD

**Issue by CaedmonW** [NeteaseYanxuan/OSSA#123]
https://github.com/NeteaseYanxuan/OSSA/blob/6573fb0252474410726b44fd09875d8ccbf38414/packages/ossa/src/utils/index.ts#L29

`newProp` 有可能会有默认值，导致其值不为`null`或`undefined`，导致合并的值有误。
比如`Modal`组件的`closeable`和`showCloseIcon`属性的默认值都是`true`，如果只指定`showCloseIcon`为`false`，合并后仍为`true`

**Comment by kiner-tang** [comment]
这种情况，如果新值有默认值的话，好像怎么处理都是不对的，就程序而言，有默认值就跟用户传了新值一样了。我们是不是把默认值的处理逻辑改一下，不再`Index.defaultProps`中定义，而是在调用`deprecatedProp `时传入默认值
