### ISSUE TITLE
Ubuntu下面编译出现： ✖ Errors:   resolve 'ossaui/dist/style/components/tabbar.scss' in '/src/pages/xxx'   Parsed request is a module

### ISSUE THREAD

**Issue by beimuaihui** [NeteaseYanxuan/OSSA#126]
### OSSA version

0.6.1

### 复现步骤

 npm install && npm run dev:weapp

### 预期表现?

运行正常

### 实际表现?

提示tabbar.scss找不到

### 环境信息

```shell
Ubuntu ,Taro 3.5.11, ossa 0.6.1
```

**Comment by CaedmonW** [comment]
引用的地方使用 `import 'ossaui/dist/style/components/tab-bar.scss'`试试看呢
