### ISSUE TITLE
Picker的选项居左

### ISSUE THREAD

**Issue by WeiCongcong** [NeteaseYanxuan/OSSA#143]
### OSSA version

0.7.1

### 复现步骤

```TypeScript
<OsPicker
  range={range}
  value={value}
>
  <OsList title="title" desc="desc" />
</OsPicker>
```

### 预期表现?

点击后选项显示在弹窗的中间

### 实际表现?

点击后选项显示在弹窗的左侧

### 其他?

在开发者工具中看到渲染出来的`custom-wrapper`没有`picker-container`这个样式，怀疑是`CustomWrapper `的样式会丢失。其它组件是有样式的，比如`View`的`picker-group`。

**Comment by CaedmonW** [comment]
目前看下来，在 `custom-wrapper` 转成真正的小程序自定义组件的时候，taro会把这个自定义组件的 `virtualHost` 设为 `false` 。导致了这个节点本身变成了一个“普通”的节点，但是目前好像没办法给这个节点上加上样式

https://github.com/NervJS/taro/blob/ba270098fe8a7ebdfd12d92d5922dbda93f393de/packages/taro-runtime/src/dsl/common.ts#L380-L383
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html

**Comment by CaedmonW** [comment]
暂时先通过不使用 `CustomWrapper` 组件的形式解决 #144
