### ISSUE TITLE
在微信开发者工具编译后OsHeaderItem text内容出不来

### ISSUE THREAD

**Issue by hugyu** [NeteaseYanxuan/OSSA#54]
### OSSA version

    "ossaui": "^0.3.3",

### 复现步骤

编译后就不能出现了

### 预期表现?

可以显示text的内容

### 实际表现?

![image](https://user-images.githubusercontent.com/92319342/198280386-ea599cd4-f351-498b-88b8-6085c68d370f.png)
![image](https://user-images.githubusercontent.com/92319342/198280433-b5f82884-14d0-4fa5-a73c-d65f1fc1acf5.png)

### 环境信息

```shell
Taro 3.5.4
```

**Comment by CaedmonW** [comment]
能提供下详细的使用方式吗？或者可否提供下可复现的demo

**Comment by hugyu** [comment]
> 能提供下详细的使用方式吗？或者可否提供下可复现的demo
不好意思，我也不知道怎么表述合适
https://github.com/hugyu/vote这是仓库地址
辛苦看一下

**Comment by CaedmonW** [comment]
我这边没能复现
<img width="328" alt="image" src="https://user-images.githubusercontent.com/107974245/198286673-064d78ea-3eac-4723-907a-9035e92e4772.png">

可以试试关闭prebundle，看看还能不能复现
https://docs.taro.zone/docs/ossa#%E5%85%B3%E9%97%AD%E7%BB%84%E4%BB%B6%E5%BA%93%E7%9A%84prebundle

**Comment by hugyu** [comment]
> 我这边没能复现 <img alt="image" width="328" src="https://user-images.githubusercontent.com/107974245/198286673-064d78ea-3eac-4723-907a-9035e92e4772.png">
> 
> 可以试试关闭prebundle，看看还能不能复现 https://docs.taro.zone/docs/ossa#%E5%85%B3%E9%97%AD%E7%BB%84%E4%BB%B6%E5%BA%93%E7%9A%84prebundle

![image](https://user-images.githubusercontent.com/92319342/198288176-a4fc4c01-0754-4e0b-9fd8-2b0b979da1a8.png)
这样写对么

**Comment by CaedmonW** [comment]
> 这样写对么

不太对，这样又被覆盖了

**Comment by hugyu** [comment]
> > 这样写对么
> 
> 不太对，这样又被覆盖了
![image](https://user-images.githubusercontent.com/92319342/198498118-aa0097f1-4755-47ab-917f-4646641fd881.png)

解决了大佬，这样就好了谢谢
