### ISSUE TITLE
使用echarts时 canvas层级比较高，与picker发生重叠

### ISSUE THREAD

**Issue by hugyu** [NeteaseYanxuan/OSSA#62]
我试了用coverview包裹，但是不起作用
![image](https://user-images.githubusercontent.com/92319342/198875414-cb956ebc-362e-4858-a30b-369bcfd2707e.png)

**Comment by CaedmonW** [comment]
哪个端的显示有问题呢？微信小程序？
麻烦提供下复现的demo
