### ISSUE TITLE
小程序使用分包后 Picker组件样式缺失

### ISSUE THREAD

**Issue by hugyu** [NeteaseYanxuan/OSSA#63]
### OSSA version

    "ossaui": "^0.3.3",

### 复现步骤

将一个页面使用分包，picker就样式缺失了

### 预期表现?

没有分包之前：
![image](https://user-images.githubusercontent.com/92319342/198941831-0922a837-bef5-41eb-8f05-eadcf64c126d.png)

### 实际表现?

![image](https://user-images.githubusercontent.com/92319342/198941797-319516a3-0f92-4fe7-9c7c-49c08daac528.png)

**Comment by CaedmonW** [comment]
```javascript
// app.scss
@import '~ossaui/dist/style/index.scss'
```
样式全局引入也有问题吗？
样式的按需加载目前应该是有点问题

**Comment by hugyu** [comment]
> ```js
> // app.scss
> @import '~ossaui/dist/style/index.scss'
> ```
> 
> 样式全局引入也有问题吗？ 样式的按需加载目前应该是有点问题

![image](https://user-images.githubusercontent.com/92319342/198953710-4779ccfd-9103-456f-9627-ac364bdcf78b.png)
就是全局的哦

**Comment by CaedmonW** [comment]
在独立分包中使用，需要在独立分包中再次单独引入下
独立分包不会引用主包app.scss中的代码

**Comment by hugyu** [comment]
> 在独立分包中使用，需要在独立分包中再次单独引入下 独立分包不会引用主包app.scss中的代码

嗷嗷，麻烦了大佬
